"""baseline schema

Revision ID: 1500cda8787b
Revises: 
Create Date: 2026-09-05 22:19:22.362122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1500cda8787b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=100), nullable=False),
    sa.Column('protocol', sa.Enum('vless', 'trojan', 'wireguard', 'hysteria2', name='hostprotocol'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('network', sa.Enum('tcp', 'ws', 'grpc', name='hostnetwork'), nullable=True),
    sa.Column('security', sa.Enum('none', 'tls', 'reality', name='hostsecurity'), nullable=True),
    sa.Column('sni', sa.String(length=255), nullable=True),
    sa.Column('reality_public_key', sa.String(length=64), nullable=True),
    sa.Column('reality_private_key', sa.String(length=64), nullable=True),
    sa.Column('reality_short_id', sa.String(length=16), nullable=True),
    sa.Column('wireguard_public_key', sa.String(length=64), nullable=True),
    sa.Column('wireguard_private_key', sa.String(length=64), nullable=True),
    sa.Column('wireguard_subnet', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'connected', 'error', name='nodestatus'), nullable=False),
    sa.Column('xray_version', sa.String(length=32), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'expired', 'limited', name='userstatus'), nullable=False),
    sa.Column('secret', sa.String(length=36), nullable=False),
    sa.Column('data_limit', sa.BigInteger(), nullable=True),
    sa.Column('used_traffic', sa.BigInteger(), nullable=False),
    sa.Column('expire', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_users_secret'), 'proxy_users', ['secret'], unique=True)
    op.create_index(op.f('ix_proxy_users_username'), 'proxy_users', ['username'], unique=True)
    op.create_table('setup_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setup_keys_key'), 'setup_keys', ['key'], unique=True)
    op.create_table('group_hosts',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'host_id')
    )
    op.create_table('group_users',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['proxy_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('wireguard_peers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('private_key', sa.String(length=64), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['proxy_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wireguard_peers')
    op.drop_table('group_users')
    op.drop_table('group_hosts')
    op.drop_index(op.f('ix_setup_keys_key'), table_name='setup_keys')
    op.drop_table('setup_keys')
    op.drop_index(op.f('ix_proxy_users_username'), table_name='proxy_users')
    op.drop_index(op.f('ix_proxy_users_secret'), table_name='proxy_users')
    op.drop_table('proxy_users')
    op.drop_table('panel_settings')
    op.drop_table('nodes')
    op.drop_table('hosts')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
