"""add telegram notification settings

Revision ID: 1594b196d6bf
Revises: 1500cda8787b
Create Date: 2026-09-05 22:30:37.031690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1594b196d6bf'
down_revision: Union[str, Sequence[str], None] = '1500cda8787b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_settings', sa.Column('telegram_bot_token', sa.String(length=255), nullable=True))
    op.add_column('panel_settings', sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panel_settings', 'telegram_chat_id')
    op.drop_column('panel_settings', 'telegram_bot_token')
    # ### end Alembic commands ###
