"""add cores

Revision ID: 24216a8b216b
Revises: 1594b196d6bf
Create Date: 2026-09-06 00:29:26.445853

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24216a8b216b'
down_revision: Union[str, Sequence[str], None] = '1594b196d6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DEFAULT_CORE_NAME = "Default Core"

cores_table = sa.table(
    "cores",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String),
    sa.column("note", sa.String),
    sa.column("created_at", sa.DateTime),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cores_name'), 'cores', ['name'], unique=True)
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('core_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_hosts_core_id_cores', 'cores', ['core_id'], ['id'])
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('core_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_nodes_core_id_cores', 'cores', ['core_id'], ['id'])
    # ### end Alembic commands ###

    # Data migration: give every pre-existing host/node a default core so
    # sync_node's core_id filter keeps matching them the same way it always
    # implicitly did (every host feeding every node) before Cores existed.
    connection = op.get_bind()
    connection.execute(
        cores_table.insert().values(name=DEFAULT_CORE_NAME, note=None, created_at=datetime.now(timezone.utc))
    )
    default_core_id = connection.execute(
        sa.text("SELECT id FROM cores WHERE name = :name").bindparams(name=DEFAULT_CORE_NAME)
    ).scalar_one()
    connection.execute(sa.text("UPDATE hosts SET core_id = :core_id WHERE core_id IS NULL").bindparams(core_id=default_core_id))
    connection.execute(sa.text("UPDATE nodes SET core_id = :core_id WHERE core_id IS NULL").bindparams(core_id=default_core_id))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_nodes_core_id_cores', type_='foreignkey')
        batch_op.drop_column('core_id')
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hosts_core_id_cores', type_='foreignkey')
        batch_op.drop_column('core_id')
    op.drop_index(op.f('ix_cores_name'), table_name='cores')
    op.drop_table('cores')
    # ### end Alembic commands ###
