package main

// Hamrang ("same-hue") is a camouflage carrier for the tunnel's TCP hop. Where
// the "spoof" transport forges the packet SOURCE to ride Iran's national-
// internet L3 allow-list, Hamrang disguises the DESTINATION and the TLS
// handshake instead: it opens what looks exactly like an ordinary browser
// HTTPS session to a permitted DOMESTIC host (a "collateral freedom" target
// the filter cannot drop without breaking a real service it must keep up),
// and carries the tunnel inside it. It is the tool for ordinary DPI days when
// the international link is present but deep-packet inspection fingerprints and
// blocks proxy traffic; spoof is the tool for a full national-internet cut.
//
// Mechanically Hamrang is the wssmux transport (TLS -> WebSocket -> mux) with
// one difference that matters: the client's TLS ClientHello is generated by
// uTLS with a real browser fingerprint, not Go's own crypto/tls fingerprint
// (which DPI trivially recognises as "not a browser"). The presented SNI is
// the domestic camouflage host. The server side is byte-for-byte a wssmux
// server, so no server change is needed beyond recognising the name.

import (
	"fmt"
	"net"
	"time"

	utls "github.com/refraction-networking/utls"
)

const transportHamrang = "hamrang"

// isTLSTransport reports whether a transport wraps its stream in TLS.
func isTLSTransport(t string) bool {
	switch t {
	case "tls", "wss", "wssmux", transportHamrang:
		return true
	}
	return false
}

// isWSTransport reports whether a transport speaks WebSocket framing over its
// (possibly TLS) stream.
func isWSTransport(t string) bool {
	switch t {
	case "ws", "wss", "wsmux", "wssmux", transportHamrang:
		return true
	}
	return false
}

// hamrangClientTLS performs the client TLS handshake for Hamrang using a real
// browser fingerprint (uTLS) so DPI sees a genuine-looking browser hello aimed
// at the camouflage SNI, rather than Go's tell-tale crypto/tls fingerprint.
// The tunnel is authenticated by the shared token, so certificate verification
// is skipped exactly as the plain-TLS path does.
func hamrangClientTLS(raw net.Conn, sni string, timeout time.Duration) (net.Conn, error) {
	if sni == "" {
		return nil, fmt.Errorf("hamrang: a camouflage SNI is required")
	}
	cfg := &utls.Config{
		ServerName:         sni,
		InsecureSkipVerify: true,
		MinVersion:         utls.VersionTLS12,
	}
	// HelloChrome_Auto tracks a current Chrome ClientHello (ALPN, GREASE,
	// extension order and all), which is what makes the handshake blend in.
	uconn := utls.UClient(raw, cfg, utls.HelloChrome_Auto)
	if timeout > 0 {
		raw.SetDeadline(time.Now().Add(timeout))
	}
	if err := uconn.Handshake(); err != nil {
		return nil, fmt.Errorf("hamrang tls handshake to %q: %w", sni, err)
	}
	return uconn, nil
}
